<?php
$case = array(
    array(
        'id'=>1,
        'name'=>'戴L',
        'title'=>'戴L - 哈弗 GSD',
        'major'=>'景观设计',
        'university'=>'同济大学',
        'theme'=>'哈佛GSD',
        'GPA'=>0,
        'thumb'=>'images/case/戴L/Dai-5.jpg',
        'images'=>array(
            'images/case/戴L/Dai-1.jpg',
            'images/case/戴L/Dai-2.jpg',
            'images/case/戴L/Dai-3.jpg',
            'images/case/戴L/Dai-4.jpg',
            'images/case/戴L/Dai-5.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>2,
        'name'=>'胡YY',
        'title'=>'胡YY - 哈佛GSD、密西根大学、华盛顿大学圣路易斯分校',
        'major'=>'建筑学',
        'university'=>'浙江科技大学',
        'GPA'=>0,
        'theme'=>'哈佛GSD、密西根大学、华盛顿大学圣路易斯分校',
        'thumb'=>'images/case/胡YY/胡YY-03.jpg',
        'images'=>array(
            'images/case/胡YY/胡YY-01.jpg',
            'images/case/胡YY/胡YY-2.jpg',
            'images/case/胡YY/胡YY-03.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>3,
        'name'=>'黄RB',
        'title'=>'黄RB - 宾夕法尼亚大学、卡耐基梅隆、佐治亚理工、华盛顿大学、华盛顿大学圣路易斯分校、加州大学洛杉矶分校',
        'major'=>'建筑学',
        'GPA'=>3.85,
        'university'=>'吉林建筑大学',
        'theme'=>'宾夕法尼亚大学、卡耐基梅隆、佐治亚理工、华盛顿大学、华盛顿大学圣路易斯分校、加州大学洛杉矶分校',
        'thumb'=>'images/case/黄RB/黄RB-03.jpg',
        'images'=>array(
            'images/case/黄RB/黄RB-01.jpg',
            'images/case/黄RB/黄RB-02.jpg',
            'images/case/黄RB/黄RB-03.jpg',
            'images/case/黄RB/黄RB-04.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>4,
        'name'=>'柳JJ',
        'title'=>'柳JJ - AA、UCL、爱丁堡、香港大学、香港中文大学',
        'major'=>'建筑学',
        'GPA'=>3.73,
        'university'=>'吉林建筑大学',
        'theme'=>'AA、UCL、爱丁堡、香港大学、香港中文大学',
        'thumb'=>'images/case/柳JJ/柳JJ-01.jpg',
        'images'=>array(
            'images/case/柳JJ/柳JJ-01.jpg',
            'images/case/柳JJ/柳JJ-02.jpg',
            'images/case/柳JJ/柳JJ-03.jpg',
            'images/case/柳JJ/柳JJ-04.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>5,
        'name'=>'施DS',
        'title'=>'施DS - 代尔夫特理工、哥伦比亚大学、加州大学伯克利分校、加州大学洛杉矶分校、华盛顿大学圣路易斯分校、佐治亚理工',
        'major'=>'城市规划',
        'GPA'=>90,
        'university'=>'同济大学',
        'theme'=>'代尔夫特理工、哥伦比亚大学、加州大学伯克利分校、加州大学洛杉矶分校、华盛顿大学圣路易斯分校、佐治亚理工',
        'thumb'=>'images/case/施DS/施DS-01.jpg',
        'images'=>array(
            'images/case/施DS/施DS-01.jpg',
            'images/case/施DS/施DS-02.jpg',
            'images/case/施DS/施DS-03.jpg',
            'images/case/施DS/施DS-04.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>6,
        'name'=>'王CX',
        'title'=>'王CX - UCL Part2',
        'major'=>'建筑学',
        'GPA'=>3.5,
        'university'=>'中央美术学院',
        'theme'=>'UCL Part2',
        'thumb'=>'images/case/王CX/王CX-01.jpg',
        'images'=>array(
            'images/case/王CX/王CX-01.jpg',
            'images/case/王CX/王CX-02.jpg',
            'images/case/王CX/王CX-03.jpg',
            'images/case/王CX/王CX-04.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>7,
        'name'=>'王GY',
        'title'=>'王GY - 密西根大学、南加州建筑学院、哥伦比亚大学、华盛顿大学圣路易斯分校',
        'major'=>'建筑学',
        'GPA'=>0,
        'university'=>'北京交通大学',
        'theme'=>'密西根大学、南加州建筑学院、哥伦比亚大学、华盛顿大学圣路易斯分校',
        'thumb'=>'images/case/王GY/王GY-03.jpg',
        'images'=>array(
            'images/case/王GY/王GY-01.jpg',
            'images/case/王GY/王GY-02.jpg',
            'images/case/王GY/王GY-03.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>8,
        'name'=>'王XL',
        'title'=>'王XL - CL （城市设计与建筑设计）',
        'major'=>'建筑学',
        'GPA'=>2.94,
        'university'=>'吉林建筑大学',
        'theme'=>'CL （城市设计与建筑设计）',
        'thumb'=>'images/case/王XL/王XL-3.jpg',
        'images'=>array(
            'images/case/王XL/王XL-1.jpg',
            'images/case/王XL/王XL-2.jpg',
            'images/case/王XL/王XL-3.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>9,
        'name'=>'王YX',
        'title'=>'王YX - UCL',
        'major'=>'园林景观设计',
        'GPA'=>80,
        'university'=>'沈阳建筑大学',
        'theme'=>'UCL',
        'thumb'=>'images/case/王YX/王YX-1.jpg',
        'images'=>array(
            'images/case/王YX/王YX-1.jpg',
            'images/case/王YX/王YX-2.jpg',
            'images/case/王YX/王YX-3.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>10,
        'name'=>'谢SS',
        'title'=>'谢SS - 剑桥大学',
        'major'=>'建筑与城市设计',
        'GPA'=>0,
        'university'=>'华中科技大学',
        'theme'=>'剑桥大学',
        'thumb'=>'images/case/谢SS/谢SS-3.jpg',
        'images'=>array(
            'images/case/谢SS/谢SS-1.jpg',
            'images/case/谢SS/谢SS-2.jpg',
            'images/case/谢SS/谢SS-3.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>11,
        'name'=>'谢SW',
        'title'=>'谢SW - 哈佛MLA2',
        'major'=>'景观学',
        'GPA'=>3.2,
        'university'=>'合肥工业大学',
        'theme'=>'哈佛MLA2',
        'thumb'=>'images/case/谢SW/谢SW-2.jpg',
        'images'=>array(
            'images/case/谢SW/谢SW-1.jpg',
            'images/case/谢SW/谢SW-2.jpg',
            'images/case/谢SW/谢SW-3.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>12,
        'name'=>'杨L',
        'title'=>'杨L - 代尔夫特理工、瑞典皇家理工、香港大学（城市设计、建筑学）',
        'major'=>'建筑',
        'GPA'=>85,
        'university'=>'太原理工大学',
        'theme'=>'代尔夫特理工、瑞典皇家理工、香港大学（城市设计、建筑学）',
        'thumb'=>'images/case/杨L/杨L-1.jpg',
        'images'=>array(
            'images/case/杨L/杨L-1.jpg',
            'images/case/杨L/杨L-2.jpg',
            'images/case/杨L/杨L-3.jpg',
            'images/case/杨L/杨L-4.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>13,
        'name'=>'余ZX',
        'title'=>'余ZX - 代尔夫特理工、爱丁堡大学、香港大学',
        'major'=>'建筑',
        'GPA'=>0,
        'university'=>'湖南大学',
        'theme'=>'代尔夫特理工、爱丁堡大学、香港大学',
        'thumb'=>'images/case/余ZX/余ZX-1.jpg',
        'images'=>array(
            'images/case/余ZX/余ZX-1.jpg',
            'images/case/余ZX/余ZX-2.jpg',
            'images/case/余ZX/余ZX-3.jpg',
        ),
        'topimg_height'=> 265,
        'topimg_width'=> 265,
        'likenums'=>0,
        'browsenums'=>0
    ),
    array(
        'id'=>14,
        'name'=>'张YB',
        'title'=>'张YB - AA（DRL建筑与城市设计）、谢菲尔德大学（建筑学）',
        'major'=>'建筑学',
        'GPA'=>78.5,
        'university'=>'华侨大学',
        'theme'=>'AA（DRL建筑与城市设计）、谢菲尔德大学（建筑学）',
        'thumb'=>'images/case/张YB/张YB-1.jpg',
        'images'=>array(
            'images/case/张YB/张YB-1.jpg',
            'images/case/张YB/张YB-2.jpg',
            'images/case/张YB/张YB-3.jpg',
        ),
        'topimg_height'=> 1186,
        'topimg_width'=> 1677,
        'likenums'=>265,
        'browsenums'=>265
    ),
);